class Question {
  final String context;
  final String option1;
  final String option2;
  final String language1;
  final String language2;

  Question({
    required this.context,
    required this.option1,
    required this.option2,
    required this.language1,
    required this.language2,
  });
}

final List<Question> questions = [
  Question(
    context: "Imagine que você chega em casa depois de um dia longo e cansativo, o trabalho foi intenso e você só quer relaxar.",
    option1: "Você prefere ouvir um elogio carinhoso sobre como você lidou bem com tudo.",
    option2: "Você prefere um abraço apertado que te faça sentir acolhido.",
    language1: "A",
    language2: "E",
  ),
  Question(
    context: "Pense em um fim de semana perfeito, com tempo livre para aproveitar como quiser, sem preocupações.",
    option1: "Você gostaria de passar horas conversando e rindo com alguém especial, sem pressa.",
    option2: "Você gostaria que alguém te ajudasse com algo prático, como organizar a casa.",
    language1: "B",
    language2: "D",
  ),
  Question(
    context: "Você está planejando um dia especial, talvez um aniversário ou uma data importante, e quer se sentir valorizado.",
    option1: "Você ficaria feliz com um presentinho surpresa que mostra que pensaram em você.",
    option2: "Você prefere uma visita longa e tranquila de alguém querido, só aproveitando a companhia.",
    language1: "C",
    language2: "B",
  ),
  Question(
    context: "Imagine que alguém quer te apoiar em um momento difícil, e você está precisando de um gesto de carinho.",
    option1: "Você prefere que façam algo útil por você, como resolver um problema prático.",
    option2: "Você prefere um toque carinhoso no ombro que te traga conforto.",
    language1: "D",
    language2: "E",
  ),
  Question(
    context: "Pense em um momento de carinho após um dia corrido, quando você só quer se sentir amado de verdade.",
    option1: "Você gosta de sentir um braço ao seu redor, te envolvendo em um abraço quente.",
    option2: "Você ficaria feliz com um presente significativo que alguém escolheu com cuidado.",
    language1: "E",
    language2: "C",
  ),
  Question(
    context: "Você está com amigos queridos em um sábado à tarde, o sol está brilhando e todos estão animados.",
    option1: "Você prefere sair e aproveitar o tempo juntos, talvez em um passeio descontraído.",
    option2: "Você gosta de um aperto de mão ou abraço que mostre a conexão entre vocês.",
    language1: "B",
    language2: "E",
  ),
  Question(
    context: "Alguém quer te mostrar que te valoriza depois de você ter feito algo importante no trabalho.",
    option1: "Você prefere ganhar algo simbólico, como um objeto que represente o momento.",
    option2: "Você prefere ouvir palavras de apoio que reconheçam seu esforço.",
    language1: "C",
    language2: "A",
  ),
  Question(
    context: "Imagine um momento relaxante em casa, com uma música suave ao fundo e um dia tranquilo pela frente.",
    option1: "Você gosta de estar bem perto de quem ama, sentindo a presença física deles.",
    option2: "Você prefere ouvir que está incrível hoje, com um elogio que te anima.",
    language1: "E",
    language2: "A",
  ),
  Question(
    context: "Pense em um dia com pessoas especiais, talvez um feriado ou um encontro casual com amigos.",
    option1: "Você ama passar tempo juntos sem pressa, conversando ou fazendo algo leve.",
    option2: "Você ficaria feliz com um mimo pequeno, como um doce ou lembrancinha.",
    language1: "B",
    language2: "C",
  ),
  Question(
    context: "Alguém quer te alegrar depois de uma semana cheia, e você está precisando de um up no ânimo.",
    option1: "Você prefere ouvir algo positivo sobre você, como um elogio inesperado.",
    option2: "Você prefere que te ajudem em algo, como arrumar algo que estava te preocupando.",
    language1: "A",
    language2: "D",
  ),
  Question(
    context: "Você está aproveitando um dia livre, o clima está perfeito e você quer aproveitar ao máximo.",
    option1: "Você quer companhia para fazer algo legal, como assistir um filme ou passear.",
    option2: "Você prefere ouvir palavras gentis que te façam sorrir.",
    language1: "B",
    language2: "A",
  ),
  Question(
    context: "Pense em como você se sente amado depois de um dia em que tudo deu errado e você precisa de apoio.",
    option1: "Você valoriza mais ações práticas, como alguém te ajudando a resolver algo.",
    option2: "Você ama um abraço inesperado que te tira o peso do dia.",
    language1: "D",
    language2: "E",
  ),
  Question(
    context: "Imagine um gesto de carinho em uma manhã tranquila, com café na mesa e um clima leve.",
    option1: "Você prefere um elogio sincero que te faça começar o dia bem.",
    option2: "Você gosta de vários presentinhos fofos, como flores ou algo feito à mão.",
    language1: "A",
    language2: "C",
  ),
  Question(
    context: "Você está com alguém especial em um fim de tarde, com o sol se pondo e uma vibe gostosa no ar.",
    option1: "Vocês conversam ou fazem algo juntos por horas, aproveitando cada segundo.",
    option2: "Você sente um toque frequente que te aproxima, como mãos dadas ou um carinho.",
    language1: "B",
    language2: "E",
  ),
  Question(
    context: "Alguém quer te impressionar depois de você ter conquistado algo grande, como um projeto concluído.",
    option1: "Você gosta de ser elogiado pelo que fez, com palavras que te motivam.",
    option2: "Você prefere um favor que não esperava, como alguém te ajudando a relaxar.",
    language1: "A",
    language2: "D",
  ),
  Question(
    context: "Pense em um momento casual em casa, com alguém querido por perto e um dia sem pressa.",
    option1: "Você ama um toque leve ao passar por você, que te faz sentir conectado.",
    option2: "Você prefere que te ouçam com atenção enquanto você conta algo do dia.",
    language1: "E",
    language2: "B",
  ),
  Question(
    context: "Você precisa de apoio em um projeto importante, o prazo está apertado e você está estressado.",
    option1: "Você prefere ajuda num projeto, alguém que coloque a mão na massa com você.",
    option2: "Você ficaria feliz com um presente carinhoso que te distraia um pouco.",
    language1: "D",
    language2: "C",
  ),
  Question(
    context: "Imagine um dia comum, você acorda cedo e está se arrumando para sair, sentindo-se bem consigo mesmo.",
    option1: "Você ama um elogio sobre seu visual que te dá confiança extra.",
    option2: "Você prefere alguém que te entenda profundamente, conversando sobre seus planos.",
    language1: "A",
    language2: "B",
  ),
  Question(
    context: "Você se sente cuidado em um dia chuvoso, quando está em casa com alguém especial e o clima pede conforto.",
    option1: "Um toque especial te faz sentir seguro, como um abraço ou mão no ombro.",
    option2: "Alguém faz algo útil por você, como preparar algo quente para vocês.",
    language1: "E",
    language2: "D",
  ),
  Question(
    context: "Pense em quem te ama em um domingo preguiçoso, com tempo para relaxar e curtir a companhia deles.",
    option1: "Você valoriza as coisas que fazem por você, como arrumar algo sem você pedir.",
    option2: "Você ama ganhar algo feito com carinho, como um desenho ou um lanche especial.",
    language1: "D",
    language2: "C",
  ),
  Question(
    context: "Você quer se sentir especial em um dia qualquer, sem motivo específico, só por estar com quem gosta.",
    option1: "Alguém te dá atenção total, ouvindo e participando do que você quer fazer.",
    option2: "Alguém te ajuda com algo importante, te tirando um peso das costas.",
    language1: "B",
    language2: "D",
  ),
  Question(
    context: "É seu aniversário e você está animado para comemorar com as pessoas que ama ao seu redor!",
    option1: "Você ama ganhar um presente legal que mostra que te conhecem bem.",
    option2: "Você prefere palavras que te emocionam, como um discurso ou mensagem carinhosa.",
    language1: "C",
    language2: "A",
  ),
  Question(
    context: "Alguém te surpreende em um dia comum, talvez com um gesto que você não esperava de jeito nenhum.",
    option1: "Você recebe um presente que te entende, algo que combina perfeitamente com você.",
    option2: "Você ganha ajuda nas tarefas do dia, tornando tudo mais leve.",
    language1: "C",
    language2: "D",
  ),
  Question(
    context: "Você está conversando em um café com alguém querido, o ambiente está calmo e acolhedor.",
    option1: "Alguém te escuta sem interrupções, prestando atenção em cada palavra sua.",
    option2: "Alguém te dá um presente de um dia especial que vocês já viveram juntos.",
    language1: "B",
    language2: "C",
  ),
  Question(
    context: "Pense num dia corrido, cheio de tarefas e compromissos, quando você mal tem tempo para respirar.",
    option1: "Você ama ajuda nas tarefas diárias, alguém que te apoie no caos.",
    option2: "Você prefere uma viagem com alguém especial, mesmo que seja só um passeio rápido.",
    language1: "D",
    language2: "B",
  ),
  Question(
    context: "Você está com alguém íntimo em uma noite tranquila, com velas acesas e um clima romântico no ar.",
    option1: "Um beijo te faz feliz, trazendo uma conexão especial no momento.",
    option2: "Um presente surpresa te anima, algo que não esperava ganhar agora.",
    language1: "E",
    language2: "C",
  ),
  Question(
    context: "Vocês estão juntos em um parque, o dia está lindo e vocês estão aproveitando a companhia um do outro.",
    option1: "Você ama ouvir que é querido, com palavras que aquecem o coração.",
    option2: "Você prefere olhares atentos enquanto fala, sentindo que estão conectados.",
    language1: "A",
    language2: "B",
  ),
  Question(
    context: "Alguém te dá algo em um momento inesperado, talvez só para te ver sorrir sem motivo especial.",
    option1: "Você ama presentes especiais que mostram que pensaram em você.",
    option2: "Você prefere um toque amigo, como um abraço ou um carinho leve.",
    language1: "C",
    language2: "E",
  ),
  Question(
    context: "Você pede algo em um dia em que está precisando de um apoio extra, talvez por estar sobrecarregado.",
    option1: "Alguém faz com entusiasmo, te ajudando com energia e vontade.",
    option2: "Alguém te diz o quanto te valoriza, com palavras que te levantam.",
    language1: "D",
    language2: "A",
  ),
  Question(
    context: "Pense no seu dia a dia, na rotina que você leva com as pessoas que ama e que estão sempre por perto.",
    option1: "Você precisa de um toque constante, como um abraço ou mão nas costas diariamente.",
    option2: "Você precisa ouvir algo bom todos os dias, como um elogio ou carinho verbal.",
    language1: "E",
    language2: "A",
  ),
];